### ISSUE TITLE
Use periods in keys

### ISSUE THREAD

**Issue by drewcrawford** [AnarchyTools/atpkg#3]
As discussed [here](https://github.com/AnarchyTools/atbuild/issues/22#issuecomment-172925555), we want to use periods in keys.

**Comment by owensd** [comment]
OK, this isn't a parser issue. This is an issue with out you've implemented overlays. 

``` clojure
    :build.osx {
      :tool "lldb-build"
      :name "json-swift-osx"
      :name.short "js-osx"
      :output-type "lib" 
      :sources ["src/**.swift" "lib/**.swift"]
    }
```

This parses just fine. Here's the branch with the tests that show it: https://github.com/AnarchyTools/atpkg/tree/iss3-keys.
