### ISSUE TITLE
Bug: atbuild does not find build tasks in included files 2 levels deep

### ISSUE THREAD

**Issue by dunkelstern** [AnarchyTools/atpkg#4]
Following structure:

Package A
- task default, dependency PackageB.default

Package B
- task default, dependency PackageC.default

Package C
- just a default task

Expected: Builds just fine

Result: fatal error: Can't find so-called task PackageC.default: file atpkg/src/Package.swift, line 187

**Comment by drewcrawford** [comment]
Claiming.  We're going to flatten multiply-imported package names, and error on trouble.
