### ISSUE TITLE
Overlays regression

### ISSUE THREAD

**Issue by drewcrawford** [AnarchyTools/atpkg#7]
In doing some QA for the next atbuild, I've noticed some regressions on issues I've previously written test coverage for, specifically related to complex overlays.  Apparently this test coverage was removed in the llbuild branch, with the net result that we no longer have coverage.

I've checked the test coverage back into llbuild branch, as well as updated (to the best of my ability) per the documentation, but we need a pass here to do a release.

For want of a better name, this advanced, previous sample is now called `overlays2`, and is derived from actual software I build, which also fails to build.  I think its failure is the same bug, but if not, I'll write more test cases.

**Comment by owensd** [comment]
Is this still an issue now that we've backed out the changes?

**Comment by drewcrawford** [comment]
No.
